### PR TITLE
Fix audio/webm files

### PR DESCRIPTION
**Pull request by kiskoza**
Hi. Recently I encountered a bug using Active Storage when I recorded some audio in a Chrome browser (only supported mimetype is `audio/webm`), uploaded it to the server and got it back as `video/webm` - which broke the frontend logic to show it in an audio player instead of a video player. During my investigation I found this gem and noticed that it doesn't know anything about `audio/webm`.

In the [WebM Project docs](https://www.webmproject.org/docs/container/), you can find the following information:
* MIME-type: video/webm
* Audio-only MIME-type: audio/webm
* Video codec: The Codec ID SHOULD be "V_VP8" or "V_VP9". 
* Audio codec: The Codec ID SHOULD be "A_VORBIS" or "A_OPUS". 

That means a video webm file should contain at least one video stream (but don't need to check for audios) and an audio webm file should contain at least one audio stream (but should not have any video streams - this rule should be after the video's). I added these rules to the `tables.rb` file with a new sample file for `audio/webm`

Is there anything else I need to add regarding these changes?

### CODE REVIEW

**Review by gmcgibbon — CHANGES_REQUESTED** [review]
The `tables.rb` file is generated using the XML data files in the repo. We recently switched from Mimemagic to Apache Tika. It seems `audio/webm` isn't a type Tika knows about. Could you please add the mime info to `data/custom.xml` and regenerate the file?

**Comment by kiskoza** [comment]
Thanks for the feedback, I added my changes to `custom.xml` and regenerated the tables (got the same result, but the new line for audio/webm moved to the audios) and force pushed all of it in one commit.

We should mention this rake task in a contribution guide to help future contributors, it was easier to make the changes there now I'm aware of this file :smile:

**Review by gmcgibbon — APPROVED** [review]
Looks great, thanks!

> We should mention this rake task in a contribution guide to help future contributors, it was easier to make the changes there now I'm aware of this file 😄

Yes, totally agree. I will look at adding this.

**Comment by ClearlyClaire** [comment]
This seems to break some webm files, for instance [this one](https://github.com/mastodon/mastodon/blob/main/spec/fixtures/files/attachment.webm), presumably because the `V_VP8` string appears after 4096 bytes.

**Pull request merged**
