### PR TITLE
Store MIME parents in a distinct Hash

### PR DESCRIPTION
**Pull request by casperisfine**
Since most entries don't have a parent, this
allows to remove one array per entry, saving about 50KiB (~10%).

Before:
```
Total retained: 506.64 kB (8558 objects)
```

After:
```
Total retained: 450.85 kB (7006 objects)
```

cc @gmcgibbon (let me know if I'm pushing this a bit too far)

### CODE REVIEW

**Review by gmcgibbon — APPROVED** [review]
> let me know if I'm pushing this a bit too far

I think the memory savings are marginal, but still worth it. Especially if the DB were to grow (via custom types etc.) this is a more efficient way to store the data. I find this format easier to reason about too, so I'll approve based on that.

Also regarding the build, considering we're still testing Ruby 2.2 on CI, we can probably bump the required ruby version. Rails requires 2.7 and any app still using 2.2 should really be upgrading their app. Let's fix that before merging this.

**Comment by casperisfine** [comment]
>  we can probably bump the required ruby version

Hum, it's very unclear to me how the buildkite pipelined is defined. It's not in the repo, so I don't know how to remove Ruby 2.2 from the list of tested ruby. @matthewd would you know?

Also I wonder if `marcel` really benefit from buildkite over regular GitHub Actions.

**Comment by gmcgibbon** [comment]
https://github.com/rails/gem-buildkite-config

The config is generated. If you bump the required ruby it should "just work" I believe.

**Comment by casperisfine** [comment]
Oh TIL, that's really neat.

**Pull request merged**
