### PR TITLE
Replace mimemagic with ruby-magic

### PR DESCRIPTION
**Pull request by georgeclaghorn**

### CODE REVIEW

**Comment by AFU92** [comment]
### Fix: 
https://github.com/rails/rails/issues/41750

**Comment by ssunday** [comment]
Is the intent still to remove `mimemagic` from `marcel` now that `mimemagic` 0.3.7 has been released under MIT https://rubygems.org/gems/mimemagic/versions/0.3.7?

**Comment by krtschmr** [comment]
I would say that it's not ideal to do it during runtime and believe the rails-core wants a more robust solution

**Comment by ssunday** [comment]
> I would say that it's not ideal to do it during runtime and believe the rails-core wants a more robust solution

Agreed! I would prefer this replacement.

**Comment by georgeclaghorn** [comment]
Closing in favor of #30.

**Pull request closed without merging**
